### ISSUE TITLE
Bug report: code in hmm.rmd

### ISSUE THREAD

**Issue by FangBigSheep** [stephens999/fiveMinuteStats#46]
In the vignette of `HMM`, file `hmm.Rmd`, in the forward algorithm

Line 80: 
> alpha[t+1,k]__ = m[k]*emit(k,X[t]) 

it seems that line should be 
> alpha[t+1,k] = m[k]*emit(k,X[t + 1]) 

Please check.

**Comment by stephens999** [comment]
fixed thanks
