### ISSUE TITLE
Missing data example in "Likelihood Ratios: examples and pitfalls" is the probability for missing data the same for both models? 

### ISSUE THREAD

**Issue by geekynils** [stephens999/fiveMinuteStats#52]
Having read the paragraph that explains how to incorporate the probability of missing data I cannot think of a reason for why it would be different in the tusk example: Both models use the same data and the probability of a failing test is therefore the same. 

However the data is weighted different because the first allele it is twice as likely in the Forest Elephant. If we had a DNA test that failed more when the allele is not present could we then conclude that the missing the first marker is more probable under M_s?

**Comment by stephens999** [comment]
So you say:
 I cannot think of a reason for why it would be different in the tusk example: Both models use the same data and the probability of a failing test is therefore the same.

But then you give an example that illustrates why it might be different! Indeed the probability of a dna test failing could depends on the underlying allele, and i think the answer to your question is "yes".

The missing data idea should probably have its own vignette....

**Comment by geekynils** [comment]
yeah, it was late last evening.
