### ISSUE TITLE
Asking for the content of Introduction to EM: Gaussian Mixture Models

### ISSUE THREAD

**Issue by ngvananh2508** [stephens999/fiveMinuteStats#66]
I am sorry. I do not report any issues, but I have one question. I tried to find the answer, but I could not get it.
<img width="642" alt="image" src="https://github.com/stephens999/fiveMinuteStats/assets/130348585/b7901e45-ac34-495c-bbef-3e0e5c819b09">
I understand this formula, but I don't comprehend the product sign in the formal part. Why is the sum sign replaced by the product sign?

<img width="621" alt="image" src="https://github.com/stephens999/fiveMinuteStats/assets/130348585/0105bf0b-252f-4ab6-96bb-c24ad69785a6">

Thank you very much for helping me.

**Comment by stephens999** [comment]
it's a bit tricky to explain in words. But let me say the two expressions are not the same.
The likelihood is P(X | mu, sigma, pi) whereas the  second expression is P(X, Z | mu, sigma, pi) = P(Z| mu, sigma,pi) p(X|mu, sigma, pi, Z) = prod_i p(Z_i |pi) p(X_i | mu, sigma, Z_i)

So to understand the second expression you need to understand the above, and then
you need to understand why p(Z_i |pi) p(X_i | mu, sigma, Z_i) = prod_k (...)  where (...) is the 
expression after the product sign above.

**Comment by ngvananh2508** [comment]
Finally, I can understand this formula. Does this expression p(Z_i |pi) p(X_i | mu, sigma, Z_i) = prod_k (...) contain only 1 term pi_k.N(x_k|mu_k, sigma_k) and the others are 1s?

Thank you very much.

**Comment by stephens999** [comment]
Yes, you got it!
