### ISSUE TITLE
Introduction to Mixture Models talks about N(20,2) but implements N(20,1)

### ISSUE THREAD

**Issue by lechten** [stephens999/fiveMinuteStats#68]
Many thanks for publishing your introductions under CC BY!
The text above the first piece of code for Mixture Models talks about a standard deviation of $2 and refers to N(20,2). The subsequent implementation and histogram use N(20,1), though. Maybe go for 2 everywhere?

**Comment by stephens999** [comment]
yes, looks like a bug. i'd welcome a pull request to fix

**Comment by lechten** [comment]
I hope PR #69 does the trick. Workflowr installation failed over here...
